title: writing & interests
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2209550619591027
  brandStrength: 0.4787234
  lightness: 0.6686755581758916
  brandColors:
    - '#E7E7DB'
    - '#1D1D1B'
    - '#D0583E'
    - '#264C7D'
    - '#7B3929'
  rhythmicContrast: 0.863161354791373
typography_spectrum: 0.8595745
layout_spectrum: 0.2531915
name: a dabbler in books&nbsp;
